### ISSUE TITLE
Should `--locked` be a default argument for the cargo build pack?

### ISSUE THREAD

**Issue by edude03** [paketo-community/cargo#152]
My coworker and I ran into an unexpected issue today, a dependency in our stack had a different version of the crate then the main library but this was fine when built locally because the lock file resolved to a version that both libraries could use. 

However, we found out that unlike `cargo build`, `cargo install` doesn't use the lock file by default, causing two different versions of the library to installed during build. 

We fixed it by adding `--locked` to the build args, however it seems like that's the behaviour you would always want anyway? Since the detect requires you to have a lock file, seems surprising that we wouldn't use it.

**Comment by dmikusa-pivotal** [comment]
It's funny you mention this. I was just reading something about this difference in behavior over the weekend. I knew about the `--locked` flag but wasn't really aware of what it did exactly (the description in `--help` isn't very clear).

I'm glad you mentioned this as I was leaning towards including it in the defaults as well. It sure seems like we should be trying to build with the exact set of dependencies from the lock file. Having someone else mention this a well makes me more confident to add it to the defaults.

It kind of makes me wonder if `cargo install` is the right choice of command to use. This is the second surprising difference between `cargo build` and `cargo install` that I've hit with the buildpack. The other was related to building a full workspace. Anyway, I'd be curious to get your thoughts on that as well. Is `cargo install` what you'd expect here? or would it make more sense to use `cargo build`?

**Comment by edude03** [comment]
IIRC the problem with `cargo build` is not knowing where the binaries end up. In [cargo2nix](https://github.com/cargo2nix/cargo2nix) we solved this by using json output from cargo and parsing it. Cargo install side steps that problem. 


On a relatedish note though, I'd still like to find a way to build the test binaries and have them in the built image, so maybe cargo build would get me closer to that

**Comment by dmikusa-pivotal** [comment]
Yes, we are pulling out binary names from cargo metadata already so it's probably not too much work to support cargo build as well. I will open a separate issue.
